/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package class_ms;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Hp
 */
public class AttendanceAdd extends javax.swing.JFrame {

    /**
     * Creates new form AttendanceAdd
     */
    public AttendanceAdd() {
        
        initComponents();
        
        txtStuid.setEditable(false);
        txtStuname.setEditable(false);
        txtClassid.setEditable(false);
        txtGrade.setEditable(false);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRoomid = new javax.swing.JTextField();
        ComboMonth = new javax.swing.JComboBox();
        ComboYear = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox5 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtStuname = new javax.swing.JTextField();
        txtStuid = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        txtClassid = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel6.setText("Mark Attendance");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 11, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 901, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Room ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Month");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Year");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 102, -1, -1));

        txtRoomid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRoomid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRoomidKeyPressed(evt);
            }
        });
        getContentPane().add(txtRoomid, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 102, 165, -1));

        ComboMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "Septhember", "October", "November", "December" }));
        getContentPane().add(ComboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 102, -1, -1));

        ComboYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", " " }));
        getContentPane().add(ComboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 102, -1, -1));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 102, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Student ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Student Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Grade");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel1.setToolTipText("Mark the attendance");
        jPanel1.setName(""); // NOI18N

        CheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox1.setText("1st Week");

        CheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox2.setText("2nd Week");

        CheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox3.setText("3rd Week");

        CheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox4.setText("4th Week");

        CheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox5.setText("Extra Week");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        jButton3.setText("Mark");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CheckBox1)
                        .addGap(28, 28, 28)
                        .addComponent(CheckBox2)
                        .addGap(33, 33, 33)
                        .addComponent(CheckBox3)
                        .addGap(39, 39, 39)
                        .addComponent(CheckBox4)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(CheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox1)
                    .addComponent(CheckBox2)
                    .addComponent(CheckBox3)
                    .addComponent(CheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 347, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/Reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/close Jframe.png"))); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Class ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name ", "Grade", "Class ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 180, 378, 236));

        txtStuname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtStuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 211, -1));

        txtStuid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtStuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 127, -1));

        txtGrade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 211, -1));

        txtClassid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtClassid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 211, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/delete.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/SBG.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String roomid=txtRoomid.getText();
        /*
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from room where room_id = '"+roomid+"'  limit 1");
            
            if(rs.next())
            {
                
                lblStuid.setText(rs.getString(2));
                lblStuname.setText(rs.getString(3));
                lblGrade.setText(rs.getString(5));
                //txtRoomid.setEditable(false);
                lblNo.setText(String.valueOf(a));
                
                //String stuid=lblStuid.getText();
                String month=ComboMonth.getSelectedItem().toString();
                String year=ComboYear.getSelectedItem().toString();
                ResultSet rs1=st.executeQuery("select * from attend where room_id = '"+roomid+"' and stu_id='"+lblStuid.getText()+"' and month='"+month+"' and year='"+year+"' ");
                
               
                
                if(rs1.next()){
                    String week1=rs1.getString(5);
                    String week2=rs1.getString(6);
                    String week3=rs1.getString(7);
                    String week4=rs1.getString(8);
                    String week5=rs1.getString(9);
                    
                    //Week1
                    if(week1.equals("1")){
                        CheckBox1.setSelected(true);
                    }
                    else
                    {
                        CheckBox1.setSelected(false);
                    }
                    //Week2
                    if(week2.equals("1")){
                        CheckBox2.setSelected(true);
                    }
                    else
                    {
                        CheckBox2.setSelected(false);
                    }
                    //Week3
                    if(week3.equals("1")){
                        CheckBox3.setSelected(true);
                    }
                    else
                    {
                        CheckBox3.setSelected(false);
                    }
                    //week4
                    if(week4.equals("1")){
                        CheckBox4.setSelected(true);
                    }
                    else
                    {
                        CheckBox4.setSelected(false);
                    }
                    //Week5
                    if(week5.equals("1")){
                        CheckBox5.setSelected(true);
                    }
                    else
                    {
                        CheckBox5.setSelected(false);
                    }
                   //CheckBox1.(rs1.get(5));
                    
                    ResultSet rs3=st.executeQuery("select count(stu_id) from attend where room_id = '"+roomid+"' and month='"+month+"' and year='"+year+"' ");
                    
                    if(rs3.next())
                    {
                        int d = rs3.getInt(1);
                        lblNo2.setText(String.valueOf(d)); 
                    }
                }
                else{
                    
                }

            }
            else
            {
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Class is does not Exist");
            }

        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,e);
        }
        
        */
        
        //Get table to data
        try{
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        
        ResultSet rsCheck=st.executeQuery("select * from student where room_id='"+roomid+"'");
            if(rsCheck.next()){
                
            }
            else{
                //lblTittle.setText("Wrong Room ID.. Please enter correct details!");
                JOptionPane.showMessageDialog(null,"Room Id is Wrong");
                this.setVisible(false);
                new AttendanceAdd().setVisible(true);
            }
        
        ResultSet rsTableStu=st.executeQuery("select * from student where room_id='"+roomid+"'"); 
        
                while(rsTableStu.next()){
                    //String no=String.valueOf(rsTable.getInt("id"));
                    String stuId= rsTableStu.getString("stu_id");
                    String stuName= rsTableStu.getString("stu_name");
                    String grade= rsTableStu.getString("grade");
                    String classId=rsTableStu.getString("class_id");
                    
                    String tbData[]= {stuId,stuName,grade,classId};
                    DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
                    tableModel.addRow(tbData);
                    
                }
                con.close();
                
                //lblTittle.setText("You are going to mark Room No: " +roomid+ " / " +"Month: "+ComboMonth.getSelectedItem()+" / "+ "Year: " +ComboYear.getSelectedItem());
                btnSearch.setVisible(false);
                txtRoomid.setEditable(false);
                
                
            
        
                
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Connection Error!");
        }
        
        /*
        txtRoomid.setEditable(false);
        ComboMonth.
        ComboYear.setEditable(false);
        */
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        String stuid=txtStuid.getText();
        String stuname=txtStuname.getText();
        String classid=txtClassid.getText();
        String grade=txtGrade.getText();
        
        if(stuid.isEmpty() || stuname.isEmpty() || classid.isEmpty() || grade.isEmpty())
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Please Click you want table row!");
        }
        
        else{
                    try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from attend where room_id = '"+roomid+"' and  month = '"+month+"' and year = '"+year+"' and stu_id='"+stuid+"'");
           
            if(rs.next()){
             
            //Week 1
            String w1 ="";
            if(CheckBox1.isSelected()){
               w1="1";
            } else {
                w1="0";
            }
            //Week 2
            String w2 ="";
            if(CheckBox2.isSelected()){
               w2="1";
            } else {
                w2="0";
            }
            //Week 3
            String w3 ="";
            if(CheckBox3.isSelected()){
               w3="1";
            } else {
                w3="0";
            }
            //Week 4
            String w4 ="";
            if(CheckBox4.isSelected()){
               w4="1";
            } else {
                w4="0";
            }
            //Week Ex
            String w5 ="";
            if(CheckBox5.isSelected()){
               w5="1";
            } else {
                w5="0";
            }
                
            //Update Query   
            PreparedStatement ps=con.prepareStatement("update attend set 1week=? , 2week=? , 3week=? , 4week=?, exweek=?, month=? , year=? where stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"'");
            ps.setString(1,w1);
            ps.setString(2,w2);
            ps.setString(3,w3);
            ps.setString(4,w4);
            ps.setString(5,w5);
            ps.setString(6,month);
            ps.setString(7,year);
            ps.executeUpdate();
            
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Successfully mark attendance!");
            }
            
            else{
              
                
               try{
            //Week 1
            String w1 ="";
            if(CheckBox1.isSelected()){
               w1="1";
            } else {
                w1="0";
            }
            //Week 2
            String w2 ="";
            if(CheckBox2.isSelected()){
               w2="1";
            } else {
                w2="0";
            }
            //Week 3
            String w3 ="";
            if(CheckBox3.isSelected()){
               w3="1";
            } else {
                w3="0";
            }
            //Week 4
            String w4 ="";
            if(CheckBox4.isSelected()){
               w4="1";
            } else {
                w4="0";
            }
            //Week Ex
            String w5 ="";
            if(CheckBox5.isSelected()){
               w5="1";
            } else {
                w5="0";
            }
            
            PreparedStatement ps=con.prepareStatement("insert into attend value(?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, roomid);
            ps.setString(2, stuid);
            ps.setString(3, stuname);
            ps.setString(4, classid);
            ps.setString(5, w1);
            ps.setString(6, w2);
            ps.setString(7, w3);
            ps.setString(8, w4);
            ps.setString(9, w5);
            ps.setString(10, month);
            ps.setString(11, year);
            
            ps.executeUpdate();
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Successfully Added");
            
            }
            catch(Exception e){
                    
                }
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
       }//null else

     
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      
        CheckBox1.setSelected(false);
        CheckBox2.setSelected(false);
        CheckBox3.setSelected(false);
        CheckBox4.setSelected(false);
        CheckBox5.setSelected(false);
        
        
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int selectRowIndex = jTable1.getSelectedRow();
        
        txtStuid.setText(model.getValueAt(selectRowIndex,0).toString());
        txtStuname.setText(model.getValueAt(selectRowIndex,1).toString());
        txtGrade.setText(model.getValueAt(selectRowIndex,2).toString());
        txtClassid.setText(model.getValueAt(selectRowIndex,3).toString());
        
        String stuid=(model.getValueAt(selectRowIndex,0).toString());
        String stuname=(model.getValueAt(selectRowIndex,1).toString());
        String grade=(model.getValueAt(selectRowIndex,2).toString());
        String classId=(model.getValueAt(selectRowIndex,3).toString());
        
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        
        try{
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        ResultSet rs1=st.executeQuery("select * from attend where room_id = '"+roomid+"' and stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"' ");
                
               
                if(rs1.next()){
                    String week1=rs1.getString(5);
                    String week2=rs1.getString(6);
                    String week3=rs1.getString(7);
                    String week4=rs1.getString(8);
                    String week5=rs1.getString(9);
                    
                    //Week1
                    if(week1.equals("1")){
                        CheckBox1.setSelected(true);
                    }
                    else
                    {
                        CheckBox1.setSelected(false);
                    }
                    //Week2
                    if(week2.equals("1")){
                        CheckBox2.setSelected(true);
                    }
                    else
                    {
                        CheckBox2.setSelected(false);
                    }
                    //Week3
                    if(week3.equals("1")){
                        CheckBox3.setSelected(true);
                    }
                    else
                    {
                        CheckBox3.setSelected(false);
                    }
                    //week4
                    if(week4.equals("1")){
                        CheckBox4.setSelected(true);
                    }
                    else
                    {
                        CheckBox4.setSelected(false);
                    }
                    //Week5
                    if(week5.equals("1")){
                        CheckBox5.setSelected(true);
                    }
                    else
                    {
                        CheckBox5.setSelected(false);
                    }
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
      this.setVisible(false);
      new AttendanceAdd().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRoomidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomidKeyPressed
        // TODO add your handling code here:
         //txtRoomid.getText().toUpperCase();
    }//GEN-LAST:event_txtRoomidKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        String stuid=txtStuid.getText();
        String stuname=txtStuname.getText();
        String classid=txtClassid.getText();
        String grade=txtGrade.getText();

        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a=JOptionPane.showConfirmDialog(jf,"Do you want to delete this record?","Select",JOptionPane.YES_NO_OPTION);

        if(a==0)
        {
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("delete from attend where room_id='"+roomid+"' and month='"+month+"' and year='"+year+"' and stu_id='"+stuid+"' and class_id='"+classid+"'");
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Record deleted successfully!");
            }
            catch(Exception e)
            {
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Connection Error");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JComboBox ComboMonth;
    private javax.swing.JComboBox ComboYear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtClassid;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtRoomid;
    private javax.swing.JTextField txtStuid;
    private javax.swing.JTextField txtStuname;
    // End of variables declaration//GEN-END:variables
}
