/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package class_ms;

import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class FeezAdd extends javax.swing.JFrame {

    /**
     * Creates new form FeezAdd
     */
    public FeezAdd() {
        initComponents();
        CheckBox1.setEnabled(false);
        CheckBox2.setEnabled(false);
        CheckBox3.setEnabled(false);
        CheckBox4.setEnabled(false);
        CheckBox5.setEnabled(false);
        
        
        
        txtStuid.setEditable(false);
        txtStuname.setEditable(false);
        txtGrade.setEditable(false);
        txtClassid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        PanelFeez = new javax.swing.JPanel();
        CheckBox1D = new javax.swing.JCheckBox();
        CheckBox2D = new javax.swing.JCheckBox();
        CheckBox3D = new javax.swing.JCheckBox();
        CheckBox4D = new javax.swing.JCheckBox();
        CheckBox5D = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRoomid = new javax.swing.JTextField();
        ComboMonth = new javax.swing.JComboBox();
        ComboYear = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        btnMonth = new javax.swing.JButton();
        CheckBoxMonth = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox5 = new javax.swing.JCheckBox();
        txtClassid = new javax.swing.JTextField();
        txtStuid = new javax.swing.JTextField();
        txtStuname = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btnMontDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel6.setText("Mark Fees");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 11, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 1085, 10));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 88, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Student ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Student Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Room ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 88, -1, -1));

        lblMonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMonth.setText("Monthly");
        getContentPane().add(lblMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, -1));

        PanelFeez.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Daily Fees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        PanelFeez.setToolTipText("Mark the Fees");
        PanelFeez.setName(""); // NOI18N

        CheckBox1D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox1D.setText("1st Week");

        CheckBox2D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox2D.setText("2nd Week");

        CheckBox3D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox3D.setText("3rd Week");

        CheckBox4D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox4D.setText("4th Week");

        CheckBox5D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox5D.setText("Extra Week");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        jButton4.setText("Mark");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/delete.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFeezLayout = new javax.swing.GroupLayout(PanelFeez);
        PanelFeez.setLayout(PanelFeezLayout);
        PanelFeezLayout.setHorizontalGroup(
            PanelFeezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFeezLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFeezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFeezLayout.createSequentialGroup()
                        .addComponent(CheckBox1D)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBox2D)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBox3D)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBox4D)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBox5D)
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFeezLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PanelFeezLayout.setVerticalGroup(
            PanelFeezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFeezLayout.createSequentialGroup()
                .addGroup(PanelFeezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox1D)
                    .addComponent(CheckBox2D)
                    .addComponent(CheckBox3D)
                    .addComponent(CheckBox4D)
                    .addComponent(CheckBox5D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(PanelFeezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );

        getContentPane().add(PanelFeez, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 629, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Month");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 88, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Year");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 88, -1, -1));

        txtRoomid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtRoomid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 88, 165, -1));

        ComboMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "Septhember", "October", "November", "December" }));
        getContentPane().add(ComboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 88, -1, -1));

        ComboYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", " " }));
        getContentPane().add(ComboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/Reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, -1, -1));

        btnMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        btnMonth.setText("Mark");
        btnMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthActionPerformed(evt);
            }
        });
        getContentPane().add(btnMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 113, 31));

        CheckBoxMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMonthActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 85, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Grade");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name ", "Grade", "Class ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 340, 240));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Class ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel2.setToolTipText("Mark the Feez");
        jPanel2.setName(""); // NOI18N

        CheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox1.setText("1st Week");

        CheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox2.setText("2nd Week");

        CheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox3.setText("3rd Week");

        CheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox4.setText("4th Week");

        CheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox5.setText("Extra Week");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckBox1)
                .addGap(18, 18, 18)
                .addComponent(CheckBox2)
                .addGap(18, 18, 18)
                .addComponent(CheckBox3)
                .addGap(18, 18, 18)
                .addComponent(CheckBox4)
                .addGap(18, 18, 18)
                .addComponent(CheckBox5)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CheckBox1)
                .addComponent(CheckBox2)
                .addComponent(CheckBox3)
                .addComponent(CheckBox4)
                .addComponent(CheckBox5))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 629, -1));

        txtClassid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtClassid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 210, -1));

        txtStuid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStuidActionPerformed(evt);
            }
        });
        getContentPane().add(txtStuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 105, -1));

        txtStuname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtStuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, -1));

        txtGrade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 210, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/close Jframe.png"))); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        btnMontDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMontDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/delete.png"))); // NOI18N
        btnMontDelete.setText("Delete");
        btnMontDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnMontDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/SBG.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxMonthActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //for Attendance
        CheckBox1.setSelected(false);
        CheckBox2.setSelected(false);
        CheckBox3.setSelected(false);
        CheckBox4.setSelected(false);
        CheckBox5.setSelected(false);
        
        //for feez
        CheckBox1D.setSelected(false);
        CheckBox2D.setSelected(false);
        CheckBox3D.setSelected(false);
        CheckBox4D.setSelected(false);
        CheckBox5D.setSelected(false);
        
        //for Monthy Pay
        CheckBoxMonth.setSelected(false);
        

        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int selectRowIndex = jTable1.getSelectedRow();

        txtStuid.setText(model.getValueAt(selectRowIndex,0).toString());
        txtStuname.setText(model.getValueAt(selectRowIndex,1).toString());
        txtGrade.setText(model.getValueAt(selectRowIndex,2).toString());
        txtClassid.setText(model.getValueAt(selectRowIndex,3).toString());

        String stuid=(model.getValueAt(selectRowIndex,0).toString());
        String stuname=(model.getValueAt(selectRowIndex,1).toString());
        String grade=(model.getValueAt(selectRowIndex,2).toString());
        String classId=(model.getValueAt(selectRowIndex,3).toString());

        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();

        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs1=st.executeQuery("select * from attend where room_id = '"+roomid+"' and stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"'  ");
            
            //for attendance
            if(rs1.next()){
                
                String week1=rs1.getString(5);
                String week2=rs1.getString(6);
                String week3=rs1.getString(4);
                String week4=rs1.getString(8);
                String week5=rs1.getString(9);

                //Week1
                if(week1.equals("1")){
                    CheckBox1.setSelected(true);
                }
                else
                {
                    CheckBox1.setSelected(false);
                }
                //Week2
                if(week2.equals("1")){
                    CheckBox2.setSelected(true);
                }
                else
                {
                    CheckBox2.setSelected(false);
                }
                //Week3
                if(week3.equals("1")){
                    CheckBox3.setSelected(true);
                }
                else
                {
                    CheckBox3.setSelected(false);
                }
                //week4
                if(week4.equals("1")){
                    CheckBox4.setSelected(true);
                }
                else
                {
                    CheckBox4.setSelected(false);
                }
                //Week5
                if(week5.equals("1")){
                    CheckBox5.setSelected(true);
                }
                else
                {
                    CheckBox5.setSelected(false);
                }
  
            }
            
        }
        
        
        catch(Exception e){ 
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Error");
        }
        
                    
            
        //for daily feez
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs2=st.executeQuery("select * from feez where room_id = '"+roomid+"' and stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"' ");

                if(rs2.next()){
                String week1=rs2.getString(6);
                String week2=rs2.getString(7);
                String week3=rs2.getString(8);
                String week4=rs2.getString(9);
                String week5=rs2.getString(10);

                //Week1
                if(week1.equals("1")){
                    CheckBox1D.setSelected(true);
                }
                else
                {
                    CheckBox1D.setSelected(false);
                }
                //Week2
                if(week2.equals("1")){
                    CheckBox2D.setSelected(true);
                }
                else
                {
                    CheckBox2D.setSelected(false);
                }
                //Week3
                if(week3.equals("1")){
                    CheckBox3D.setSelected(true);
                }
                else
                {
                    CheckBox3D.setSelected(false);
                }
                //week4
                if(week4.equals("1")){
                    CheckBox4D.setSelected(true);
                }
                else
                {
                    CheckBox4D.setSelected(false);
                }
                //Week5
                if(week5.equals("1")){
                    CheckBox5D.setSelected(true);
                }
                else
                {
                    CheckBox5D.setSelected(false);
                }
            }
        }
        catch(Exception e){/*
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Error");*/
        }
        
        
        
        
        //for monthly feez
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs3=st.executeQuery("select * from feez_month where room_id = '"+roomid+"' and stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"' ");

                if(rs3.next()){
                Boolean pay=rs3.getBoolean(6);
                

                
                if(pay.equals(true)){
                    CheckBoxMonth.setSelected(true);
                }
                else
                {
                    CheckBoxMonth.setSelected(false);
                }
            
            }
        }
        catch(Exception e){/*
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Error");*/
        }
        
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        String roomid=txtRoomid.getText();
        //Get table to data
        try{
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        
        ResultSet rsCheck=st.executeQuery("select * from student where room_id='"+roomid+"'");
            if(rsCheck.next()){
                
            }
            else{
                //lblTittle.setText("Wrong Room ID.. Please enter correct details!");
                JOptionPane.showMessageDialog(null,"Room Id is Wrong");
                
            }
        
        ResultSet rsTableStu=st.executeQuery("select * from student where room_id='"+roomid+"'"); 
        
                while(rsTableStu.next()){
                    //String no=String.valueOf(rsTable.getInt("id"));
                    String stuId= rsTableStu.getString("stu_id");
                    String stuName= rsTableStu.getString("stu_name");
                    String grade= rsTableStu.getString("grade");
                    String classId=rsTableStu.getString("class_id");
                    
                    String tbData[]= {stuId,stuName,grade,classId};
                    DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
                    tableModel.addRow(tbData);
                    
                }
                con.close();
                
                //lblTittle.setText("You are going to mark Room No: " +roomid+ " / " +"Month: "+ComboMonth.getSelectedItem()+" / "+ "Year: " +ComboYear.getSelectedItem());
                btnSearch.setVisible(false);
                txtRoomid.setEditable(false);
               
        }
        catch(Exception e){
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connection Error!");
        }
        
        
       
        //when feez type monthly oe daily disposing suitabale panal
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
        
            ResultSet rsFeezType=st.executeQuery("select fezz_type from room where room_id='"+roomid+"'");
            while(rsFeezType.next()){
                String feezType = rsFeezType.getString("fezz_type");
                if(feezType.equals("Daily")){
                    lblMonth.setVisible(false);
                    CheckBoxMonth.setEnabled(false);
                    btnMonth.setVisible(false);
                    btnMontDelete.setVisible(false);
                }
                else{
                     PanelFeez.setVisible(false);
                }
                
                
            }
           
   
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        String stuid=txtStuid.getText();
        String stuname=txtStuname.getText();
        String classid=txtClassid.getText();
        String grade=txtGrade.getText();
        
        if(stuid.isEmpty() || stuname.isEmpty() || classid.isEmpty() || grade.isEmpty()){

            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Please Click you want table row!");
       
        }//null if
        else{
            
            try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from feez where room_id = '"+roomid+"' and  month = '"+month+"' and year = '"+year+"' and stu_id='"+stuid+"'");

            if(rs.next()){

                //Week 1
                String w1 ="";
                if(CheckBox1D.isSelected()){
                    w1="1";
                } else {
                    w1="0";
                }
                //Week 2
                String w2 ="";
                if(CheckBox2D.isSelected()){
                    w2="1";
                } else {
                    w2="0";
                }
                //Week 3
                String w3 ="";
                if(CheckBox3D.isSelected()){
                    w3="1";
                } else {
                    w3="0";
                }
                //Week 4
                String w4 ="";
                if(CheckBox4D.isSelected()){
                    w4="1";
                } else {
                    w4="0";
                }
                //Week Ex
                String w5 ="";
                if(CheckBox5D.isSelected()){
                    w5="1";
                } else {
                    w5="0";
                }
                
                //feez month
                String w6 ="";
                if(CheckBoxMonth.isSelected()){
                    w6="1";
                } else {
                    w6="0";
                }

                //Update Payement
                int count=0;
                int D1=Integer.parseInt(w1);
                int D2=Integer.parseInt(w2);
                int D3=Integer.parseInt(w3);
                int D4=Integer.parseInt(w4);
                int D5=Integer.parseInt(w5);
                    
                int total=D1+D2+D3+D4+D5;
                
                
                ResultSet rsFeez=st.executeQuery("select * from room where room_id='"+roomid+"'");
                if(rsFeez.next()){
                        
                int feez = rsFeez.getInt(4);
                String s=Integer.toString(feez);
                int FinalTot=total*feez;
                    
                //Update Query
                PreparedStatement ps=con.prepareStatement("update feez set 1week=? , 2week=? , 3week=? , 4week=?, exweek=?, month=? , year=? , count=? where stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"'");
                ps.setString(1,w1);
                ps.setString(2,w2);
                ps.setString(3,w3);
                ps.setString(4,w4);
                ps.setString(5,w5);
                ps.setString(6,month);
                ps.setString(7,year);
                ps.setInt(8, FinalTot);
                ps.executeUpdate();

                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Successfully mark Payment!");
                //Update Payment   
                }
            }

            else{
                    //Week 1
                    String w1 ="";
                    if(CheckBox1D.isSelected()){
                        w1="1";
                    } else {
                        w1="0";
                    }
                    //Week 2
                    String w2 ="";
                    if(CheckBox2D.isSelected()){
                        w2="1";
                    } else {
                        w2="0";
                    }
                    //Week 3
                    String w3 ="";
                    if(CheckBox3D.isSelected()){
                        w3="1";
                    } else {
                        w3="0";
                    }
                    //Week 4
                    String w4 ="";
                    if(CheckBox4D.isSelected()){
                        w4="1";
                    } else {
                        w4="0";
                    }
                    //Week Ex
                    String w5 ="";
                    if(CheckBox5D.isSelected()){
                        w5="1";
                    } else {
                        w5="0";
                    }
                    
            int count=0;
            int D1=Integer.parseInt(w1);
            int D2=Integer.parseInt(w2);
            int D3=Integer.parseInt(w3);
            int D4=Integer.parseInt(w4);
            int D5=Integer.parseInt(w5);
                    
            int total=D1+D2+D3+D4+D5;
                    
            
                   
            ResultSet rsFeez=st.executeQuery("select * from room where room_id='"+roomid+"'");
            if(rsFeez.next()){
                        
                    int feez = rsFeez.getInt(4);
                    String s=Integer.toString(feez);
                    int FinalTot=total*feez;
                    
                    
                    PreparedStatement ps=con.prepareStatement("insert into feez(room_id,stu_id,stu_name,class_id,grade,1week,2week,3week,4week,exweek,month,year,count,feez_type)"
                            + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, roomid);
                    ps.setString(2, stuid);
                    ps.setString(3, stuname);
                    ps.setString(4, classid);
                    ps.setString(5, grade);
                    ps.setString(6, w1);
                    ps.setString(7, w2);
                    ps.setString(8, w3);
                    ps.setString(9, w4);
                    ps.setString(10, w5);
                    ps.setString(11, month);
                    ps.setString(12, year);
                    ps.setInt(13, FinalTot);
                    ps.setString(14, "Daily");
                   
                    
                    ps.executeUpdate();
                    JFrame jf=new JFrame();
                    jf.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(jf,"Successfully Monthly Payement");
                    }
            
                else{
                
                }
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null," Connection Error");
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthActionPerformed
        // TODO add your handling code here:
        
        
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        String stuid=txtStuid.getText();
        String stuname=txtStuname.getText();
        String classid=txtClassid.getText();
        String grade=txtGrade.getText();
        
        if(stuid.isEmpty() || stuname.isEmpty() || classid.isEmpty() || grade.isEmpty()){
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Sorry you are adding empty values");
        
        }//nul if
        
        else{
            
            try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rsFeez=st.executeQuery("select * from room where room_id='"+roomid+"'");
            if(rsFeez.next()){
                int feez = rsFeez.getInt(4);
                //String s=Integer.toString(feez);
                if(CheckBoxMonth.isSelected()){
                    ResultSet rsCheck=st.executeQuery("select * from feez_month where room_id = '"+roomid+"' and stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"'");
                    if(rsCheck.next()){
                    
                        PreparedStatement ps1=con.prepareStatement("update feez_month set pay=? , count=? where stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"' and room_id='"+roomid+"'");
                        ps1.setString(1, "1");
                        ps1.setInt(2, feez);
                        
                        ps1.executeUpdate();
                        JFrame jf=new JFrame();
                        jf.setAlwaysOnTop(true);
                        JOptionPane.showMessageDialog(jf,"Successfully Added");
                    }
                    else{
                    PreparedStatement ps=con.prepareStatement("insert into feez_month(room_id,stu_id,stu_name,class_id,grade,pay,month,year,count) values(?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, roomid);
                    ps.setString(2, stuid);
                    ps.setString(3, stuname);
                    ps.setString(4, classid);
                    ps.setString(5, grade);
                    ps.setString(6, "1");
                    ps.setString(7, month);
                    ps.setString(8, year);
                    ps.setInt(9, feez);
                    
                    ps.executeUpdate();
                    JFrame jf=new JFrame();
                    jf.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(jf,"Successfully Added");
                    }
                }
                else{
                     ResultSet rsCheck2=st.executeQuery("select * from feez_month where room_id = '"+roomid+"' and stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"'");
                     if(rsCheck2.next()){
                    
                        PreparedStatement ps1=con.prepareStatement("update feez_month set pay=? , count=? where stu_id='"+stuid+"' and month='"+month+"' and year='"+year+"' and room_id='"+roomid+"'");
                        ps1.setString(1, "1");
                        ps1.setInt(2, 0);
                        
                        ps1.executeUpdate();
                        JFrame jf=new JFrame();
                        jf.setAlwaysOnTop(true);
                        JOptionPane.showMessageDialog(jf,"Successfully Added");
                    }
                     else{
                    PreparedStatement ps=con.prepareStatement("insert into feez_month(room_id,stu_id,stu_name,class_id,grade,pay,month,year,count) values(?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, roomid);
                    ps.setString(2, stuid);
                    ps.setString(3, stuname);
                    ps.setString(4, classid);
                    ps.setString(5, grade);
                    ps.setString(6, "1");
                    ps.setString(7, month);
                    ps.setString(8, year);
                    ps.setInt(9, 0);
                    
                    ps.executeUpdate();
                    JFrame jf=new JFrame();
                    jf.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(jf,"Successfully Added");
                     }
                }
            }
        }
        catch(Exception e){
            
        }
       }
        
        
    }//GEN-LAST:event_btnMonthActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      this.setVisible(false);
      new FeezAdd().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        String stuid=txtStuid.getText();
        String stuname=txtStuname.getText();
        String classid=txtClassid.getText();
        String grade=txtGrade.getText();
        
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a=JOptionPane.showConfirmDialog(jf,"Do you want to delete this record?","Select",JOptionPane.YES_NO_OPTION);

        if(a==0)
        {
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("delete from feez where room_id='"+roomid+"' and month='"+month+"' and year='"+year+"' and stu_id='"+stuid+"' and class_id='"+classid+"'");
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Record deleted successfully!");
            }
            catch(Exception e)
            {
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Connection Error");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtStuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStuidActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnMontDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontDeleteActionPerformed
        // TODO add your handling code here:
        String roomid=txtRoomid.getText();
        String month=ComboMonth.getSelectedItem().toString();
        String year=ComboYear.getSelectedItem().toString();
        String stuid=txtStuid.getText();
        String stuname=txtStuname.getText();
        String classid=txtClassid.getText();
        String grade=txtGrade.getText();
        
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a=JOptionPane.showConfirmDialog(jf,"Do you want to delete this record?","Select",JOptionPane.YES_NO_OPTION);

        if(a==0)
        {
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("delete from feez_month where room_id='"+roomid+"' and month='"+month+"' and year='"+year+"' and stu_id='"+stuid+"' and class_id='"+classid+"'");
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Record deleted successfully!");
            }
            catch(Exception e)
            {
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Connection Error");
            }
        }
    }//GEN-LAST:event_btnMontDeleteActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeezAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeezAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeezAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeezAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeezAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox1D;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox2D;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox3D;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox4D;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JCheckBox CheckBox5D;
    private javax.swing.JCheckBox CheckBoxMonth;
    private javax.swing.JComboBox ComboMonth;
    private javax.swing.JComboBox ComboYear;
    private javax.swing.JPanel PanelFeez;
    private javax.swing.JButton btnMontDelete;
    private javax.swing.JButton btnMonth;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JTextField txtClassid;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtRoomid;
    private javax.swing.JTextField txtStuid;
    private javax.swing.JTextField txtStuname;
    // End of variables declaration//GEN-END:variables
}
