/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package class_ms;


import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class homepage extends javax.swing.JFrame {
public int z=0;
public int x=0;
public int y=0;
public int a=0;
public int b=0;

public int r=0;

StuAdd AddStu=new StuAdd();
StuEdit EditStu=new StuEdit();
StuDelete DeleteStu=new StuDelete();

ClassAdd ClassAdd=new ClassAdd();
ClassEdit ClassEdit=new ClassEdit();
ClassDelete ClassDelete=new ClassDelete();

RoomAdd RoomA=new RoomAdd();
RoomEdit RoomE=new RoomEdit();
RoomDelete RoomD=new RoomDelete();

AttendanceAdd Attendance=new AttendanceAdd();
FeezAdd Feez = new FeezAdd();

ReportAttendance ReportAtt=new ReportAttendance();
ReportFeezMonth ReportFeez=new ReportFeezMonth();
ReportRoom ReportR=new ReportRoom();
ReportStudent ReportStu=new ReportStudent();
ReportFeezDaily ReportFeezD=new ReportFeezDaily();


    public homepage() {
        initComponents();
        btnstuadd.setVisible(false);
        btnstuedit.setVisible(false);
        btnstudelete.setVisible(false);
        
        btnclassadd.setVisible(false);
        btnclassedit.setVisible(false);
        btnclassdelete.setVisible(false);
        
        btnroomadd.setVisible(false);
        btnroomedit.setVisible(false);
        btnroomdelete.setVisible(false);
        
        btnattadd.setVisible(false);
        //btnattedit.setVisible(false);
        //btnattdelete.setVisible(false);
        
        btnfeezadd.setVisible(false);
        //btnfeezedit.setVisible(false);
        //btnfeezdelete.setVisible(false);
        
        btnStu.setVisible(false);
        btnAtte.setVisible(false);
        btnFee.setVisible(false);
        btnRoo.setVisible(false);
        btnFeeD.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRoom = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnFeez = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnroomadd = new javax.swing.JButton();
        btnroomedit = new javax.swing.JButton();
        btnroomdelete = new javax.swing.JButton();
        btnattadd = new javax.swing.JButton();
        btnfeezadd = new javax.swing.JButton();
        btnClass = new javax.swing.JButton();
        btnclassadd = new javax.swing.JButton();
        btnclassedit = new javax.swing.JButton();
        btnclassdelete = new javax.swing.JButton();
        btnstudelete = new javax.swing.JButton();
        btnstuedit = new javax.swing.JButton();
        btnstuadd = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnFee = new javax.swing.JButton();
        btnAtte = new javax.swing.JButton();
        btnRoo = new javax.swing.JButton();
        btnStu = new javax.swing.JButton();
        btnFeeD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRoom.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/classroom.png"))); // NOI18N
        btnRoom.setText("Room");
        btnRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRoomMouseClicked(evt);
            }
        });
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 0, 162, 65));

        btnAttendance.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/attendance.png"))); // NOI18N
        btnAttendance.setText("Attendance");
        btnAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAttendanceMouseClicked(evt);
            }
        });
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 65));

        btnFeez.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnFeez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/feez.png"))); // NOI18N
        btnFeez.setText("Feez");
        btnFeez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFeezMouseClicked(evt);
            }
        });
        btnFeez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeezActionPerformed(evt);
            }
        });
        getContentPane().add(btnFeez, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 0, 162, 65));

        btnReport.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/report.png"))); // NOI18N
        btnReport.setText("Report");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 0, 162, 65));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/Logout_1.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 72, -1));

        btnroomadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnroomadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/add.png"))); // NOI18N
        btnroomadd.setText("Add");
        btnroomadd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnroomaddComponentShown(evt);
            }
        });
        btnroomadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroomaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnroomadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 75, 99, -1));

        btnroomedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnroomedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        btnroomedit.setText("Edit");
        btnroomedit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnroomeditComponentShown(evt);
            }
        });
        btnroomedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroomeditActionPerformed(evt);
            }
        });
        getContentPane().add(btnroomedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 110, 99, -1));

        btnroomdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnroomdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/delete.png"))); // NOI18N
        btnroomdelete.setText("Delete");
        btnroomdelete.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnroomdeleteComponentShown(evt);
            }
        });
        btnroomdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroomdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnroomdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 145, -1, -1));

        btnattadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnattadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        btnattadd.setText("Mark");
        btnattadd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnattaddComponentShown(evt);
            }
        });
        btnattadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnattadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 75, 99, -1));

        btnfeezadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfeezadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        btnfeezadd.setText("Mark");
        btnfeezadd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnfeezaddComponentShown(evt);
            }
        });
        btnfeezadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeezaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnfeezadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 75, 99, -1));

        btnClass.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/class_1.png"))); // NOI18N
        btnClass.setText("Class");
        btnClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClassMouseClicked(evt);
            }
        });
        btnClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassActionPerformed(evt);
            }
        });
        getContentPane().add(btnClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 0, 162, 65));

        btnclassadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclassadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/add.png"))); // NOI18N
        btnclassadd.setText("Add");
        btnclassadd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnclassaddComponentShown(evt);
            }
        });
        btnclassadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclassaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnclassadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 75, 99, -1));

        btnclassedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclassedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        btnclassedit.setText("Edit");
        btnclassedit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnclasseditComponentShown(evt);
            }
        });
        btnclassedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclasseditActionPerformed(evt);
            }
        });
        getContentPane().add(btnclassedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 110, 99, -1));

        btnclassdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclassdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/delete.png"))); // NOI18N
        btnclassdelete.setText("Delete");
        btnclassdelete.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnclassdeleteComponentShown(evt);
            }
        });
        btnclassdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclassdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnclassdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 145, -1, -1));

        btnstudelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnstudelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/delete.png"))); // NOI18N
        btnstudelete.setText("Delete");
        btnstudelete.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnstudeleteComponentShown(evt);
            }
        });
        btnstudelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnstudelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));

        btnstuedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnstuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/save.png"))); // NOI18N
        btnstuedit.setText("Edit");
        btnstuedit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnstueditComponentShown(evt);
            }
        });
        btnstuedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstueditActionPerformed(evt);
            }
        });
        getContentPane().add(btnstuedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 99, -1));

        btnstuadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnstuadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/add.png"))); // NOI18N
        btnstuadd.setText("Add");
        btnstuadd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnstuaddComponentShown(evt);
            }
        });
        btnstuadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstuaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnstuadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 99, -1));

        btnStudent.setBackground(new java.awt.Color(255, 255, 255));
        btnStudent.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/student.png"))); // NOI18N
        btnStudent.setText("Student");
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 65));

        btnFee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/fees.png"))); // NOI18N
        btnFee.setText("Fees Month");
        btnFee.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnFeeComponentShown(evt);
            }
        });
        btnFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 140, -1));

        btnAtte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/attendance_1.png"))); // NOI18N
        btnAtte.setText("Attendance");
        btnAtte.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnAtteComponentShown(evt);
            }
        });
        btnAtte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtte, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 140, -1));

        btnRoo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/class.png"))); // NOI18N
        btnRoo.setText("Room & Class");
        btnRoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRooActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1178, 120, -1, -1));

        btnStu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/student_1.png"))); // NOI18N
        btnStu.setText("Student");
        btnStu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnStuComponentShown(evt);
            }
        });
        btnStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuActionPerformed(evt);
            }
        });
        getContentPane().add(btnStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 140, -1));

        btnFeeD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFeeD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/fees.png"))); // NOI18N
        btnFeeD.setText("Fees Daily");
        btnFeeD.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnFeeDComponentShown(evt);
            }
        });
        btnFeeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeDActionPerformed(evt);
            }
        });
        getContentPane().add(btnFeeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1178, 160, 153, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/class_ms/woodBG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomMouseClicked
        // TODO add your handling code here:
        if(y==0)
        {
            try{
                Thread.sleep(250);
                btnroomadd.setVisible(true);
            }
            catch(Exception e)
            {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
            }
        }
        else{
            btnroomadd.setVisible(false);
            btnroomedit.setVisible(false);
            btnroomdelete.setVisible(false);
            y=0;
        }
    }//GEN-LAST:event_btnRoomMouseClicked

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRoomActionPerformed

    private void btnAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttendanceMouseClicked
        // TODO add your handling code here:
        if(a==0)
        {
            try{
                Thread.sleep(250);
                btnattadd.setVisible(true);
            }
            catch(Exception e)
            {
                   JFrame jf=new JFrame();
                   jf.setAlwaysOnTop(true);
                   JOptionPane.showMessageDialog(jf,"Connectio Error");
            }
        }
        else{
            btnattadd.setVisible(false);
            //btnattedit.setVisible(false);
            //btnattdelete.setVisible(false);
            a=0;
        }
    }//GEN-LAST:event_btnAttendanceMouseClicked

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnFeezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFeezMouseClicked
        // TODO add your handling code here:
        if(b==0)
        {
            try{
                Thread.sleep(250);
                btnfeezadd.setVisible(true);
            }
            catch(Exception e)
            {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
            }
        }
        else{
            btnfeezadd.setVisible(false);
            //btnfeezedit.setVisible(false);
            //btnfeezdelete.setVisible(false);
            b=0;
        }
    }//GEN-LAST:event_btnFeezMouseClicked

    private void btnFeezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeezActionPerformed

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // TODO add your handling code here:
        if(r==0)
        {
            try{
                Thread.sleep(250);
                btnStu.setVisible(true);
            }
            catch(Exception e)
            {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
            }
        }
        else{
            btnStu.setVisible(false);
            btnAtte.setVisible(false);
            btnFee.setVisible(false);
            btnRoo.setVisible(false);
            btnFeeD.setVisible(false);
            r=0;
        }
    }//GEN-LAST:event_btnReportMouseClicked

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a= JOptionPane.showConfirmDialog(jf, "Do you really want to Exit Application","Select",JOptionPane.YES_NO_OPTION);

        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnroomaddComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnroomaddComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnroomedit.setVisible(true);
            y=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnroomaddComponentShown

    private void btnroomaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroomaddActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(true);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnroomaddActionPerformed

    private void btnroomeditComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnroomeditComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnroomdelete.setVisible(true);
            y=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnroomeditComponentShown

    private void btnroomeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroomeditActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(true);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnroomeditActionPerformed

    private void btnroomdeleteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnroomdeleteComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroomdeleteComponentShown

    private void btnattaddComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnattaddComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            //btnattedit.setVisible(true);
            a=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnattaddComponentShown

    private void btnattaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattaddActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(true);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnattaddActionPerformed

    private void btnfeezaddComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnfeezaddComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            //btnfeezedit.setVisible(true);
            b=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnfeezaddComponentShown

    private void btnfeezaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeezaddActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(true);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnfeezaddActionPerformed

    private void btnClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClassMouseClicked
        // TODO add your handling code here:
        if(x==0)
        {
            try{
                Thread.sleep(250);
                btnclassadd.setVisible(true);
            }
            catch(Exception e)
            {

            }
        }
        else{
            btnclassadd.setVisible(false);
            btnclassedit.setVisible(false);
            btnclassdelete.setVisible(false);
            x=0;
        }
    }//GEN-LAST:event_btnClassMouseClicked

    private void btnClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClassActionPerformed

    private void btnclassaddComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnclassaddComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnclassedit.setVisible(true);
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnclassaddComponentShown

    private void btnclassaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclassaddActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(true);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnclassaddActionPerformed

    private void btnclasseditComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnclasseditComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnclassdelete.setVisible(true);
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
        x=1;
    }//GEN-LAST:event_btnclasseditComponentShown

    private void btnclasseditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclasseditActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(true);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnclasseditActionPerformed

    private void btnclassdeleteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnclassdeleteComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclassdeleteComponentShown

    private void btnstudeleteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnstudeleteComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_btnstudeleteComponentShown

    private void btnstueditComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnstueditComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnstudelete.setVisible(true);
            z=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnstueditComponentShown

    private void btnstueditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstueditActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(true);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnstueditActionPerformed

    private void btnstuaddComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnstuaddComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnstuedit.setVisible(true);
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnstuaddComponentShown

    private void btnstuaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstuaddActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(true);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnstuaddActionPerformed

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        // TODO add your handling code here:
        if(z==0)
        {
            try{
                Thread.sleep(250);
                btnstuadd.setVisible(true);
            }
            catch(Exception e)
            {
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Connectio Error");
            }
        }
        else{
            btnstuadd.setVisible(false);
            btnstuedit.setVisible(false);
            btnstudelete.setVisible(false);
            z=0;
        }
    }//GEN-LAST:event_btnStudentMouseClicked

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnstudeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudeleteActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(true);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
       
    }//GEN-LAST:event_btnstudeleteActionPerformed

    private void btnclassdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclassdeleteActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(true);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnclassdeleteActionPerformed

    private void btnroomdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroomdeleteActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(true);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnroomdeleteActionPerformed

    private void btnStuComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnStuComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnAtte.setVisible(true);
            r=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnStuComponentShown

    private void btnAtteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnAtteComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnFee.setVisible(true);
            r=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnAtteComponentShown

    private void btnFeeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnFeeComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnFeeD.setVisible(true);
            r=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
    }//GEN-LAST:event_btnFeeComponentShown

    private void btnStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(true);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnStuActionPerformed

    private void btnAtteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtteActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(true);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnAtteActionPerformed

    private void btnFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(true);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnFeeActionPerformed

    private void btnRooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRooActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(true);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(false);
    }//GEN-LAST:event_btnRooActionPerformed

    private void btnFeeDComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnFeeDComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            btnRoo.setVisible(true);
            r=1;
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connectio Error");
        }
        
    }//GEN-LAST:event_btnFeeDComponentShown

    private void btnFeeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeDActionPerformed
        // TODO add your handling code here:
        AddStu.setVisible(false);
        EditStu.setVisible(false);
        DeleteStu.setVisible(false);
            
        ClassAdd.setVisible(false);
        ClassEdit.setVisible(false);
        ClassDelete.setVisible(false);
        
        RoomA.setVisible(false);
        RoomE.setVisible(false);
        RoomD.setVisible(false);
        
        Attendance.setVisible(false);
        Feez.setVisible(false);
        
        ReportAtt.setVisible(false);
        ReportFeez.setVisible(false);
        ReportR.setVisible(false);
        ReportStu.setVisible(false);
        ReportFeezD.setVisible(true);
    }//GEN-LAST:event_btnFeeDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtte;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnClass;
    private javax.swing.JButton btnFee;
    private javax.swing.JButton btnFeeD;
    private javax.swing.JButton btnFeez;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnRoo;
    private javax.swing.JButton btnRoom;
    private javax.swing.JButton btnStu;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnattadd;
    private javax.swing.JButton btnclassadd;
    private javax.swing.JButton btnclassdelete;
    private javax.swing.JButton btnclassedit;
    private javax.swing.JButton btnfeezadd;
    private javax.swing.JButton btnroomadd;
    private javax.swing.JButton btnroomdelete;
    private javax.swing.JButton btnroomedit;
    private javax.swing.JButton btnstuadd;
    private javax.swing.JButton btnstudelete;
    private javax.swing.JButton btnstuedit;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
